# Generated by Django 5.0.6 on 2024-06-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_pictures/')),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='code_link',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='project_image',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_image',
            field=models.ManyToManyField(blank=True, to='webpages.projectimage'),
        ),
    ]
