# Generated by Django 5.0.6 on 2024-06-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_projectimage_remove_portfolio_code_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='icon',
            field=models.CharField(default='default_icon', max_length=300),
        ),
    ]
